controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    mecanum_cont:
      type: mecanum_drive_controller/MecanumDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_cont:
  ros__parameters:
    reference_timeout: 0.9

    # Joint names for mecanum wheels (matching URDF)
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.212

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    linear:
      x:
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.5
        max_deceleration: -1.5
      y:
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.5
        max_deceleration: -1.5
    angular:
      z:
        max_velocity: 2.0
        min_velocity: -2.0
        max_acceleration: 2.5
        max_deceleration: -2.5

    cmd_vel_timeout: 0.5
