controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker_plugins: ["progress_checker"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      vx_samples: 20
      vy_samples: 0
      vtheta_samples: 20
      sim_time: 1.5

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
