controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 15.0
    min_vel_x: 0.0
    max_vel_x: 0.6
    max_vel_theta: 1.2
    acc_lim_x: 0.6
    acc_lim_theta: 2.5

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.0
      max_vel_x: 0.6
      max_vel_theta: 1.2
      acc_lim_x: 0.6
      acc_lim_theta: 2.5
      vx_samples: 20
      vy_samples: 0
      vtheta_samples: 20
      sim_time: 1.5
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2

      critics: [
        "RotateToGoal",
        "ObstacleFootprint",
        "PathAlign",
        "PathDist",
        "GoalAlign",
        "GoalDist",
        "Twirling"
      ]

      RotateToGoal:
        scale: 32.0
      ObstacleFootprint:
        scale: 10.0
      PathAlign:
        scale: 32.0
      PathDist:
        scale: 32.0
      GoalAlign:
        scale: 24.0
      GoalDist:
        scale: 24.0
      Twirling:
        scale: 2.0

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node

behavior_server:
  ros__parameters:
    use_sim_time: true

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - controller_server
      - planner_server
      - bt_navigator
      - behavior_server
