twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      navigation:
        topic   : /mecanum_cont/reference
        timeout : 0.5
        priority: 10
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
      joystick:
        topic   : /mecanum_cont/reference
        timeout : 0.5
        priority: 100